### ISSUE TITLE
Installation Difficulties

### ISSUE THREAD

**Issue by RemyThePianist** [Yujia-Yan/Transkun#20]
Hello Newbie Here!

I am trying to install the latest version of this, and I am coming up with some rather odd... difficulties.  (It is kind of embarrassing that this is labeled as "simple", yet I am having so much trouble. Hah)

Is there any way you could provide a YouTube tutorial on installation? I did as you suggested in the ReadMe, and I am coming up with nothing. Such as "Requirement already satisfied:"  (which I figured is that all the packages needed for setup are already located in my python packages from the previous attempts at installing) but, the issue is that "$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name" Keeps appearing? 

I've tried it in the CodeSpaces (GitHub), Studio Code, Github Desktop, etc... And same issue every time. 

A tutorial or a Google Collab would be lovely. 

Thank you for all you do!

**Comment by Yujia-Yan** [comment]
Hi, I have included one colab notebook in the readme. https://colab.research.google.com/drive/1XuFNdYbcHBy3OyGCmtt2UGa2-PXjkJeo?usp=sharing

**Comment by RemyThePianist** [comment]
Thank you! I didn't see this, my apologies! 

Do you plan on updating it to the current version once you are done with the current update you are working on?

**Comment by RemyThePianist** [comment]
Hello! I uninstalled Python and other similar programs to start from scratch. The code is running fine but, coming up with an error regarding past versions of the transkun..  I have little knowledge with coding and I may have misunderstood something regarding the installation but, this is the error:



ERROR: Cannot install transkun==0.1.3, transkun==0.1.4, transkun==2.0.0 and transkun==2.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    transkun 2.0.1 depends on torchaudio
    transkun 2.0.0 depends on torchaudio
    transkun 0.1.4 depends on torchaudio
    transkun 0.1.3 depends on torchaudio
    
    
    
    
    
    
I did not change anything with the installation process as I downloaded the zip and unzipped it and ran the "pip3 install transkun" as intended.

**Comment by Yujia-Yan** [comment]
Hi, it's the lasted version as documented in my ISMIR paper. 
I don't know why pip tries to install all versions at the same time. It could just be an issue of specific pip version. Try specify only the current latest version "pip3 install transkun==2.0.1"

**Comment by RemyThePianist** [comment]
Hello! I believe it has something to do with my python version? This is the error that occurs when using the command, "pip3 install transkun==2.0.1":

INFO: pip is looking at multiple versions of transkun to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement torchaudio (from transkun) (from versions: none)
ERROR: No matching distribution found for torchaudio

If you could direct me to which verison I should install, I will do that and try again! Let me know if there is any additional programs related to python, pip, etc.. that I should also install that isn't included in the requirements.txt/setup.py. Thank very much!

**Comment by Yujia-Yan** [comment]
Now it says your python version is higher than what the current version of torchaudio supports.  On my system I use python 3.10.

**Comment by RemyThePianist** [comment]
Hey, Yujia! So, the suggestion for using python 3.10 WORKED!! Which is great, but now I am left with another problem.. (sorry). So, when installed all requirements are met (satisfied). So, I know that everything is correctly installed and no errors whatsoever. BUT, I am having trouble running the command for transcribing a audio. 

In my directory, "C:\Users\(REDACTED)\Downloads\Transkun-main\Transkun-main" I have a audio recording for a piano piece I am trying to transcribe. When opening up the CMD/Python and using the command with "$ transkun ______" it says,

____________________________________________
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
____________________________________________
    
    
And I am not understanding why because all programs and requirements for the transkun installation are met and satisfied. Yet, no command is working. 

Additionally, when testing other commands to execute the transcribing process like "transkun ____" (without the $ symbol) it starts to process something but, ends with an error.

____________________________________________
C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\transkun\transcribe.py:49: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(path, map_location = device)
C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\Scripts\transkun.exe\__main__.py", line 7, in <module>
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\transkun\transcribe.py", line 72, in main
    fs, audio= readAudio(audioPath)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\transkun\transcribe.py", line 12, in readAudio
    audio = pydub.AudioSegment.from_file(path)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
____________________________________________

Any other information you could possible help with would be greatly appreciated and thank you for all you do!

And, when typing out "input.mp3" and "output.mid" I should be putting them in PATH form to where the mp3 is located, yes? (Because, that is what I have been doing. Although, I have tried both with PATH and without. Both resulted in error.)

**Comment by Yujia-Yan** [comment]
$ symbol should not be included in the command. 
Firstly, it says ffmpeg is not found. You can follow the instructions in https://github.com/jiaaro/pydub to install avconv and add it to PATH.
Regarding windows path, you should be able to drag a file into the command line and get its path.

**Comment by RemyThePianist** [comment]
Sounds good! I have completed that step. I added it to my PATH. I believe it is working correctly now! Thank you so much!

Although, I do have a quick question, even though it works is the following message suppose to show everytime I transcribe something?

___________________________________


C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\transkun\transcribe.py:49: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(path, map_location = device)
C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_dynamo\eval_frame.py:632: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
C:\Users\conno\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(


___________________________________

**Comment by Yujia-Yan** [comment]
They are some mandatory changes for future versions of Pytorch that I haven't addressed. They are left for future work.  :smiley_cat:

**Comment by RemyThePianist** [comment]
Ah! Awesome! Do you have a viewable roadmap for current and future plans with the program? 

I'd love to see what you got planned for the future, hah. Well I am glad everything is working as intended! Thank you for all the help.
